apiVersion: 1

datasources:
  - name: Acty PostgreSQL
    uid: acty-pg
    type: postgres
    url: acty-postgres:5432
    database: acty-postgres
    user: acty
    secureJsonData:
      password: acty
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
