package com.acty.ui.screens

import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.outlined.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.shadow
import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.acty.ui.theme.*

// ── SharingScreen ─────────────────────────────────────────────────────────────

@Composable
fun SharingScreen(sessionId: String, onBack: () -> Unit) {
    var mechanicLinkGenerated by remember { mutableStateOf(false) }
    var mechanicExpiry        by remember { mutableStateOf("24 hours") }
    val expiryOptions = listOf("2 hours", "24 hours", "7 days", "30 days")

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(
                Brush.verticalGradient(
                    colors = listOf(StatusBlueBg, Color(0xFFF8FAFC)),
                    startY = 0f, endY = 600f,
                )
            )
            .verticalScroll(rememberScrollState())
            .systemBarsPadding()
            .padding(bottom = 32.dp),
    ) {
        SharingHeader(sessionId = sessionId, onBack = onBack)

        Spacer(Modifier.height(20.dp))

        SectionHeader(title = "Verified Report")
        Spacer(Modifier.height(10.dp))
        VerifiedReportCard(sessionId = sessionId)

        Spacer(Modifier.height(20.dp))

        SectionHeader(title = "Mechanic Link")
        Spacer(Modifier.height(10.dp))
        MechanicLinkCard(
            expiry     = mechanicExpiry,
            expiryOpts = expiryOptions,
            onExpiry   = { mechanicExpiry = it },
            generated  = mechanicLinkGenerated,
            onGenerate = { mechanicLinkGenerated = true },
        )

        Spacer(Modifier.height(20.dp))

        SectionHeader(title = "Share Report")
        Spacer(Modifier.height(10.dp))
        SocialShareRow()

        Spacer(Modifier.height(20.dp))

        SectionHeader(title = "Export")
        Spacer(Modifier.height(10.dp))
        ExportOptionsCard()
    }
}

// ── Sharing Header ────────────────────────────────────────────────────────────

@Composable
fun SharingHeader(sessionId: String, onBack: () -> Unit) {
    Box(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 20.dp, vertical = 20.dp),
    ) {
        Column {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Box(
                    modifier = Modifier
                        .size(36.dp)
                        .shadow(3.dp, RoundedCornerShape(10.dp), spotColor = Color.Black.copy(alpha = 0.06f))
                        .clip(RoundedCornerShape(10.dp))
                        .background(Color.White)
                        .border(0.5.dp, BgBorder, RoundedCornerShape(10.dp))
                        .clickable(onClick = onBack),
                    contentAlignment = Alignment.Center,
                ) {
                    Icon(Icons.Filled.ArrowBack, "Back", tint = TextSecondary, modifier = Modifier.size(18.dp))
                }
                Spacer(Modifier.width(12.dp))
                Text(
                    text  = "Share Session",
                    style = MaterialTheme.typography.headlineMedium.copy(
                        fontWeight = FontWeight.Black,
                        color      = TextPrimary,
                    ),
                )
            }
            Spacer(Modifier.height(6.dp))
            Text(
                text  = sessionId.removeSuffix(".csv").removePrefix("acty_obd_"),
                style = MaterialTheme.typography.bodySmall.copy(color = TextDim),
                modifier = Modifier.padding(start = 48.dp),
            )
        }
    }
}

// ── Verified Report Card ──────────────────────────────────────────────────────

@Composable
fun VerifiedReportCard(sessionId: String) {
    ActyCard(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 20.dp),
    ) {
        Column(Modifier.padding(20.dp)) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Box(
                    modifier = Modifier
                        .size(40.dp)
                        .clip(RoundedCornerShape(12.dp))
                        .background(StatusGreenBg),
                    contentAlignment = Alignment.Center,
                ) {
                    Icon(Icons.Outlined.Verified, null, tint = StatusGreenDim, modifier = Modifier.size(22.dp))
                }
                Spacer(Modifier.width(12.dp))
                Column {
                    Text(
                        "Ed25519 Signed PDF",
                        style = MaterialTheme.typography.titleMedium.copy(color = TextPrimary),
                    )
                    Text(
                        "RFC 3161 timestamped · QR verification",
                        style = MaterialTheme.typography.bodySmall,
                    )
                }
            }

            Spacer(Modifier.height(16.dp))

            listOf(
                "Cryptographically signed with Ed25519",
                "RFC 3161 DigiCert TSA timestamp",
                "QR code links to verify endpoint",
                "Hash-chain root embedded in report",
                "Court-admissible format",
            ).forEach { feature ->
                Row(Modifier.padding(vertical = 3.dp), verticalAlignment = Alignment.Top) {
                    Icon(Icons.Filled.Check, null, tint = StatusGreenDim, modifier = Modifier.size(14.dp))
                    Spacer(Modifier.width(8.dp))
                    Text(feature, style = MaterialTheme.typography.bodySmall.copy(color = TextPrimary))
                }
            }

            Spacer(Modifier.height(16.dp))

            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .shadow(4.dp, RoundedCornerShape(14.dp), spotColor = StatusGreenDim.copy(alpha = 0.15f))
                    .clip(RoundedCornerShape(14.dp))
                    .background(Brush.linearGradient(listOf(StatusGreenDim, StatusGreen)))
                    .clickable {}
                    .padding(vertical = 14.dp),
                contentAlignment = Alignment.Center,
            ) {
                Row(
                    verticalAlignment     = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                ) {
                    Icon(Icons.Outlined.PictureAsPdf, null, tint = Color.White, modifier = Modifier.size(18.dp))
                    Text(
                        "Generate Verified Report",
                        style = MaterialTheme.typography.titleSmall.copy(
                            color      = Color.White,
                            fontWeight = FontWeight.SemiBold,
                        ),
                    )
                }
            }
        }
    }
}

// ── Mechanic Link Card ────────────────────────────────────────────────────────

@Composable
fun MechanicLinkCard(
    expiry:     String,
    expiryOpts: List<String>,
    onExpiry:   (String) -> Unit,
    generated:  Boolean,
    onGenerate: () -> Unit,
) {
    var dropdownOpen by remember { mutableStateOf(false) }

    ActyCard(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 20.dp),
    ) {
        Column(Modifier.padding(20.dp)) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Box(
                    modifier = Modifier
                        .size(40.dp)
                        .clip(RoundedCornerShape(12.dp))
                        .background(StatusBlueBg),
                    contentAlignment = Alignment.Center,
                ) {
                    Icon(Icons.Outlined.Link, null, tint = StatusBlue, modifier = Modifier.size(22.dp))
                }
                Spacer(Modifier.width(12.dp))
                Column {
                    Text(
                        "Mechanic Link",
                        style = MaterialTheme.typography.titleMedium.copy(color = TextPrimary),
                    )
                    Text(
                        "Read-only, time-limited, no account required",
                        style = MaterialTheme.typography.bodySmall,
                    )
                }
            }

            Spacer(Modifier.height(14.dp))

            Row(
                modifier              = Modifier.fillMaxWidth(),
                verticalAlignment     = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.SpaceBetween,
            ) {
                Text("Link expires in:", style = MaterialTheme.typography.bodyMedium.copy(color = TextSecondary))
                Box {
                    Row(
                        modifier = Modifier
                            .shadow(3.dp, RoundedCornerShape(100.dp), spotColor = Color.Black.copy(alpha = 0.05f))
                            .clip(RoundedCornerShape(100.dp))
                            .background(Color.White)
                            .border(0.5.dp, BgBorder, RoundedCornerShape(100.dp))
                            .clickable { dropdownOpen = true }
                            .padding(horizontal = 12.dp, vertical = 8.dp),
                        verticalAlignment = Alignment.CenterVertically,
                    ) {
                        Text(expiry, style = MaterialTheme.typography.labelMedium.copy(color = StatusBlue))
                        Spacer(Modifier.width(4.dp))
                        Icon(Icons.Filled.ArrowDropDown, null, tint = TextDim, modifier = Modifier.size(16.dp))
                    }
                    DropdownMenu(
                        expanded         = dropdownOpen,
                        onDismissRequest = { dropdownOpen = false },
                        modifier         = Modifier.background(Color.White),
                    ) {
                        expiryOpts.forEach { opt ->
                            DropdownMenuItem(
                                text    = { Text(opt, style = MaterialTheme.typography.bodyMedium.copy(color = TextPrimary)) },
                                onClick = { onExpiry(opt); dropdownOpen = false },
                            )
                        }
                    }
                }
            }

            Spacer(Modifier.height(14.dp))

            if (generated) {
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .shadow(3.dp, RoundedCornerShape(12.dp), spotColor = StatusBlue.copy(alpha = 0.10f))
                        .clip(RoundedCornerShape(12.dp))
                        .background(StatusBlueBg)
                        .border(0.5.dp, StatusBlue.copy(alpha = 0.25f), RoundedCornerShape(12.dp))
                        .padding(12.dp),
                ) {
                    Column {
                        Text("Mechanic link ready", style = MaterialTheme.typography.titleSmall.copy(color = StatusBlue))
                        Spacer(Modifier.height(4.dp))
                        Text(
                            text  = "https://verify.acty-labs.com/m/abc123xyz",
                            style = MaterialTheme.typography.bodySmall.copy(color = TextPrimary),
                        )
                        Spacer(Modifier.height(8.dp))
                        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                            ShareActionChip(icon = Icons.Outlined.ContentCopy, label = "Copy",  onClick = {})
                            ShareActionChip(icon = Icons.Outlined.Share,       label = "Share", onClick = {})
                        }
                    }
                }
            } else {
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .shadow(4.dp, RoundedCornerShape(14.dp), spotColor = StatusBlue.copy(alpha = 0.15f))
                        .clip(RoundedCornerShape(14.dp))
                        .background(Brush.linearGradient(listOf(CactusBlue, CactusBlueMid)))
                        .clickable(onClick = onGenerate)
                        .padding(vertical = 14.dp),
                    contentAlignment = Alignment.Center,
                ) {
                    Row(
                        verticalAlignment     = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(8.dp),
                    ) {
                        Icon(Icons.Outlined.Link, null, tint = Color.White, modifier = Modifier.size(18.dp))
                        Text(
                            "Generate Mechanic Link",
                            style = MaterialTheme.typography.titleSmall.copy(
                                color      = Color.White,
                                fontWeight = FontWeight.SemiBold,
                            ),
                        )
                    }
                }
            }
        }
    }
}

// ── Social Share Row ──────────────────────────────────────────────────────────

@Composable
fun SocialShareRow() {
    val platforms = listOf(
        Triple(Icons.Outlined.Share,   "Share",   CactusBlue),
        Triple(Icons.Outlined.Message, "SMS",     StatusGreenDim),
        Triple(Icons.Outlined.Email,   "Email",   StatusBlue),
        Triple(Icons.Outlined.Forum,   "Discord", AccentPurple),
    )

    Row(
        modifier              = Modifier
            .fillMaxWidth()
            .padding(horizontal = 20.dp),
        horizontalArrangement = Arrangement.spacedBy(10.dp),
    ) {
        platforms.forEach { (icon, label, color) ->
            SocialChip(icon = icon, label = label, color = color, modifier = Modifier.weight(1f))
        }
    }
}

@Composable
fun SocialChip(icon: ImageVector, label: String, color: Color, modifier: Modifier = Modifier) {
    Box(
        modifier = modifier
            .shadow(4.dp, RoundedCornerShape(14.dp), spotColor = color.copy(alpha = 0.10f))
            .clip(RoundedCornerShape(14.dp))
            .background(Color.White)
            .border(0.5.dp, color.copy(alpha = 0.15f), RoundedCornerShape(14.dp))
            .clickable {}
            .padding(vertical = 14.dp),
        contentAlignment = Alignment.Center,
    ) {
        Column(
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.spacedBy(6.dp),
        ) {
            Box(
                modifier = Modifier
                    .size(32.dp)
                    .clip(RoundedCornerShape(10.dp))
                    .background(color.copy(alpha = 0.08f)),
                contentAlignment = Alignment.Center,
            ) {
                Icon(icon, null, tint = color, modifier = Modifier.size(18.dp))
            }
            Text(label, style = MaterialTheme.typography.labelSmall.copy(color = TextSecondary))
        }
    }
}

// ── Export Options Card ───────────────────────────────────────────────────────

@Composable
fun ExportOptionsCard() {
    ActyCard(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 20.dp),
    ) {
        Column {
            ExportOption(
                icon    = Icons.Outlined.TableChart,
                label   = "CSV + Signature File",
                detail  = "Raw OBD data with .sig Ed25519 signature",
                onClick = {},
            )
            HorizontalDivider(color = BgBorder, thickness = 0.5.dp, modifier = Modifier.padding(horizontal = 16.dp))
            ExportOption(
                icon    = Icons.Outlined.DataObject,
                label   = ".acty File (CBOR/COSE)",
                detail  = "Phase 2 binary format — AES-256-GCM + Merkle root",
                onClick = {},
            )
            HorizontalDivider(color = BgBorder, thickness = 0.5.dp, modifier = Modifier.padding(horizontal = 16.dp))
            ExportOption(
                icon    = Icons.Outlined.Description,
                label   = "Plain Text Report",
                detail  = "Human-readable session summary",
                onClick = {},
            )
        }
    }
}

@Composable
fun ExportOption(icon: ImageVector, label: String, detail: String, onClick: () -> Unit) {
    Row(
        modifier          = Modifier
            .fillMaxWidth()
            .clickable(onClick = onClick)
            .padding(horizontal = 16.dp, vertical = 14.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Box(
            modifier = Modifier
                .size(36.dp)
                .clip(RoundedCornerShape(10.dp))
                .background(CactusBluePale),
            contentAlignment = Alignment.Center,
        ) {
            Icon(icon, null, tint = CactusBlue, modifier = Modifier.size(18.dp))
        }
        Spacer(Modifier.width(14.dp))
        Column(Modifier.weight(1f)) {
            Text(label, style = MaterialTheme.typography.titleSmall.copy(color = TextPrimary))
            Text(detail, style = MaterialTheme.typography.bodySmall)
        }
        Icon(Icons.Filled.ChevronRight, null, tint = TextDim, modifier = Modifier.size(18.dp))
    }
}

@Composable
fun ShareActionChip(icon: ImageVector, label: String, onClick: () -> Unit) {
    Row(
        modifier = Modifier
            .shadow(3.dp, RoundedCornerShape(100.dp), spotColor = StatusBlue.copy(alpha = 0.08f))
            .clip(RoundedCornerShape(100.dp))
            .background(Color.White)
            .border(0.5.dp, StatusBlue.copy(alpha = 0.25f), RoundedCornerShape(100.dp))
            .clickable(onClick = onClick)
            .padding(horizontal = 12.dp, vertical = 6.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Icon(icon, null, tint = StatusBlue, modifier = Modifier.size(14.dp))
        Spacer(Modifier.width(4.dp))
        Text(label, style = MaterialTheme.typography.labelMedium.copy(color = StatusBlue))
    }
}
